### ISSUE TITLE
Units in "Data" table on the main screen aren't converting if they have been changed in Settings. And and on the "Statistics" screen as well

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#79]
![Screenshot at Aug 27 12-18-12](https://user-images.githubusercontent.com/47991168/91431563-382e7400-e869-11ea-941a-83b311cae150.png)
![Screenshot at Aug 27 12-18-45](https://user-images.githubusercontent.com/47991168/91431581-3cf32800-e869-11ea-8391-465912ff2582.png)

**Comment by Artem-Kalmykov** [comment]
@qwqatest Please confirm it is fixed.

**Comment by qwqatest** [comment]
> @qwqatest Please confirm it is fixed.

Not fixed on Statistic graph 
![Screenshot at Sep 04 17-31-32](https://user-images.githubusercontent.com/47991168/92251519-a2808d80-eed5-11ea-98ba-51fc2ada380b.png)
